const STORAGE_KEY='episode_os_v1_entries';
const FILTER_KEY='episode_os_v1_filter';
const DRAFT_KEY='episode_os_v1_draft';
const THEME_KEY='episode_os_v1_theme';
const CONFIG={type:['Conversation','Work','Transit','Family','Solo','Other'],duration:['<15 min','15–60 min','60+ min'],intensity:['Low','Medium','High'],quality:[{label:'+2 Energizing',score:2},{label:'+1 Positive',score:1},{label:'0 Neutral',score:0},{label:'-1 Draining',score:-1},{label:'-2 Depleting',score:-2}]};
let draft=loadDraft(); let deferredPrompt=null;
function byId(id){return document.getElementById(id);}
function loadDraft(){try{return JSON.parse(localStorage.getItem(DRAFT_KEY))||{};}catch{return {};}}
function saveDraft(){localStorage.setItem(DRAFT_KEY,JSON.stringify(draft));}
function getEntries(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||[];}catch{return [];}}
function saveEntries(entries){localStorage.setItem(STORAGE_KEY,JSON.stringify(entries));}
function getFilter(){return localStorage.getItem(FILTER_KEY)||'All';}
function setFilter(v){localStorage.setItem(FILTER_KEY,v);}
function todayKey(dateIso){const d=dateIso?new Date(dateIso):new Date(); return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function todayEntries(){return getEntries().filter(e=>e.dayKey===todayKey());}
function renderChoiceRow(mountId,key,compact=false){const mount=byId(mountId); mount.innerHTML=''; CONFIG[key].forEach(opt=>{const label=typeof opt==='string'?opt:opt.label; const btn=document.createElement('button'); btn.type='button'; btn.className='option-btn'+(compact?' compact':'')+(draft[key]===label?' active':''); btn.textContent=label; btn.addEventListener('click',()=>{draft[key]=label; saveDraft(); renderCaptureUI();}); mount.appendChild(btn);});}
function renderCaptureUI(){renderChoiceRow('typeRow','type'); renderChoiceRow('durationRow','duration'); renderChoiceRow('intensityRow','intensity'); renderChoiceRow('qualityRow','quality',true); byId('titleInput').value=draft.title||''; byId('notesInput').value=draft.notes||'';}
function classForNet(score){if(score>0)return 'green'; if(score<0)return 'red'; return 'neutral';}
function qualityScore(label){const found=CONFIG.quality.find(i=>i.label===label); return found?found.score:null;}
function allRequiredFilled(){return !!(draft.type&&draft.duration&&draft.intensity&&draft.quality);}
function immediateRead(entry){if(entry.score>=2)return 'Strongly energizing episode. This added real lift to the day.'; if(entry.score===1)return 'Positive episode. This supported your capacity.'; if(entry.score===0)return 'Neutral episode. Useful to log because it still occupied space.'; if(entry.score===-1)return 'Draining episode. Worth comparing against the rest of the day.'; return 'Depleting episode. This likely deserves protection, boundaries, or follow-up.';}
function saveEpisode(){draft.title=byId('titleInput').value.trim(); draft.notes=byId('notesInput').value.trim(); if(!allRequiredFilled()){alert('Complete type, duration, intensity, and quality before saving.'); return;} const entry={id:String(Date.now()),dayKey:todayKey(),timestamp:new Date().toISOString(),type:draft.type,duration:draft.duration,intensity:draft.intensity,quality:draft.quality,score:qualityScore(draft.quality),title:draft.title||'',notes:draft.notes||''}; const entries=getEntries(); entries.push(entry); saveEntries(entries); byId('saveFeedbackCard').classList.remove('hidden'); byId('savedHeadline').textContent=entry.title?entry.title:entry.type+' saved'; byId('savedSub').textContent=immediateRead(entry); byId('savedBadge').textContent=entry.score>0?('+'+entry.score):String(entry.score); byId('savedBadge').className='score-badge '+classForNet(entry.score); const readWrap=byId('savedRead'); readWrap.innerHTML=''; ['Type: '+entry.type,'Duration: '+entry.duration,'Intensity: '+entry.intensity,'Quality: '+entry.quality].forEach(text=>{const el=document.createElement('div'); el.className='list-item'; el.textContent=text; readWrap.appendChild(el);}); resetForm(false); renderSummary(); renderTimeline(); renderInsights();}
function resetForm(clearFeedback=true){draft={}; saveDraft(); renderCaptureUI(); if(clearFeedback)byId('saveFeedbackCard').classList.add('hidden');}
function renderSummary(){const entries=todayEntries(); const net=entries.reduce((s,e)=>s+e.score,0); byId('netScore').textContent=net>0?('+'+net):String(net); byId('netScore').className=classForNet(net); byId('episodeCount').textContent=String(entries.length); byId('episodeCount').className='neutral'; byId('netMeta').textContent=entries.length?(net>0?'Net positive day so far.':net<0?'Net draining day so far.':'Balanced day so far.'):'No episodes logged yet.'; byId('todayDatePill').textContent=new Date().toLocaleDateString([], { month:'short', day:'numeric' }); if(entries.length){const latest=entries[entries.length-1]; byId('lastSavedPill').textContent='Last saved: '+new Date(latest.timestamp).toLocaleTimeString([], { hour:'numeric', minute:'2-digit' });} else {byId('lastSavedPill').textContent='Last saved: —';}}
function renderFilters(){const wrap=byId('filterWrap'); const current=getFilter(); const filters=['All','Energizing','Neutral','Draining']; wrap.innerHTML=''; filters.forEach(filter=>{const btn=document.createElement('button'); btn.type='button'; btn.className='filter-chip'+(current===filter?' active':''); btn.textContent=filter; btn.addEventListener('click',()=>{setFilter(filter); renderFilters(); renderTimeline();}); wrap.appendChild(btn);});}
function filteredEntries(){const all=todayEntries(); const filter=getFilter(); if(filter==='All')return all; if(filter==='Energizing')return all.filter(e=>e.score>0); if(filter==='Neutral')return all.filter(e=>e.score===0); return all.filter(e=>e.score<0);}
function renderTimeline(){renderFilters(); const wrap=byId('timelineList'); const entries=filteredEntries().slice().reverse(); wrap.innerHTML=''; if(!entries.length){wrap.innerHTML='<div class="list-item">No episodes match this filter yet.</div>'; return;} entries.forEach(entry=>{const el=document.createElement('div'); el.className='list-item'; const safeNotes=(entry.notes||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'); el.innerHTML=`<div class="timeline-episode-top"><div><strong class="${classForNet(entry.score)}">${entry.title||entry.type}</strong><div class="small">${new Date(entry.timestamp).toLocaleTimeString([], { hour:'numeric', minute:'2-digit' })}</div></div><span class="type-chip">${entry.score>0?('+'+entry.score):entry.score}</span></div><div class="small">${entry.type} • ${entry.duration} • ${entry.intensity} • ${entry.quality}</div>${safeNotes?`<div style="margin-top:8px;">${safeNotes}</div>`:''}`; wrap.appendChild(el);});}
function renderInsights(){const wrap=byId('insightList'); const entries=todayEntries(); wrap.innerHTML=''; if(!entries.length){wrap.innerHTML='<div class="list-item">Log a few episodes and this section will start reading the day back to you.</div>'; return;} const net=entries.reduce((s,e)=>s+e.score,0); const energizing=entries.filter(e=>e.score>0).length; const neutral=entries.filter(e=>e.score===0).length; const draining=entries.filter(e=>e.score<0).length; const typeCounts={}; entries.forEach(e=>{typeCounts[e.type]=(typeCounts[e.type]||0)+1;}); const topType=Object.entries(typeCounts).sort((a,b)=>b[1]-a[1])[0]; const longDraining=entries.filter(e=>e.score<0&&e.duration==='60+ min').length; const reads=['Net score today: '+(net>0?('+'+net):net)+'.','Episodes today: '+entries.length+' total — '+energizing+' energizing, '+neutral+' neutral, '+draining+' draining.',topType?'Most common episode type today: '+topType[0]+'.':'No dominant episode type yet.',longDraining?'There were '+longDraining+' long draining episodes today. Those likely deserve the most attention.':'No long draining episodes logged today so far.']; reads.forEach(text=>{const el=document.createElement('div'); el.className='list-item'; el.textContent=text; wrap.appendChild(el);});}
function exportJson(){const payload={exportedAt:new Date().toISOString(), entries:todayEntries()}; downloadFile('episode-os-export.json',JSON.stringify(payload,null,2),'application/json');}
function exportCsv(){const entries=todayEntries(); const header=['timestamp','title','type','duration','intensity','quality','score','notes']; const rows=entries.map(e=>[e.timestamp,e.title,e.type,e.duration,e.intensity,e.quality,String(e.score),e.notes]); const csv=[header,...rows].map(row=>row.map(cell=>'"'+String(cell).replaceAll('"','""')+'"').join(',')).join('\n'); downloadFile('episode-os-export.csv',csv,'text/csv');}
function clearToday(){if(!confirm('Clear all Episode OS entries for today?'))return; const remaining=getEntries().filter(e=>e.dayKey!==todayKey()); saveEntries(remaining); renderSummary(); renderTimeline(); renderInsights(); byId('saveFeedbackCard').classList.add('hidden');}
function downloadFile(filename,content,type){const blob=new Blob([content],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=filename; a.click(); URL.revokeObjectURL(url);}
function switchTab(which){const tabs={Capture:byId('viewCapture'),Timeline:byId('viewTimeline'),Insights:byId('viewInsights')}; Object.entries(tabs).forEach(([name,el])=>{el.classList.toggle('hidden',name!==which); byId('tab'+name).classList.toggle('active',name===which);}); if(which==='Timeline')renderTimeline(); if(which==='Insights')renderInsights();}
function applyTheme(theme){document.documentElement.setAttribute('data-theme',theme); localStorage.setItem(THEME_KEY,theme); byId('themeBtn').textContent=theme==='dark'?'Light':'Dark';}
function initTheme(){const saved=localStorage.getItem(THEME_KEY)||'dark'; applyTheme(saved); byId('themeBtn').addEventListener('click',()=>{const next=document.documentElement.getAttribute('data-theme')==='dark'?'light':'dark'; applyTheme(next);});}
function initInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault(); deferredPrompt=e; byId('installBtn').classList.remove('hidden');}); byId('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return; deferredPrompt.prompt(); await deferredPrompt.userChoice; deferredPrompt=null; byId('installBtn').classList.add('hidden');});}
function initServiceWorker(){if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js').catch(()=>{});}}
function wireEvents(){byId('titleInput').addEventListener('input',e=>{draft.title=e.target.value; saveDraft();}); byId('notesInput').addEventListener('input',e=>{draft.notes=e.target.value; saveDraft();}); byId('saveEpisodeBtn').addEventListener('click',saveEpisode); byId('resetCaptureBtn').addEventListener('click',()=>resetForm()); byId('tabCapture').addEventListener('click',()=>switchTab('Capture')); byId('tabTimeline').addEventListener('click',()=>switchTab('Timeline')); byId('tabInsights').addEventListener('click',()=>switchTab('Insights')); byId('exportJsonBtn').addEventListener('click',exportJson); byId('exportCsvBtn').addEventListener('click',exportCsv); byId('clearTodayBtn').addEventListener('click',clearToday);}
function boot(){initTheme(); renderCaptureUI(); renderSummary(); renderTimeline(); renderInsights(); wireEvents(); initInstall(); initServiceWorker();}
boot();
